### ISSUE TITLE
tabUniqueId怎么获取

### ISSUE THREAD

**Issue by 279838089** [hui-z/mcm#1]
tabUniqueId是跟账号的，怎么获取的到，或者规则如何产生？

**Comment by LKI** [comment]
拿tab的uniqueId就可以了。

首先要调`calendarItems/list`的接口来获取点单的日历，大概会得到这么一个数据结构：
```
[
  [tab1, tab2],
  [tab3, tab4]...
]
```

每个tab就是一餐饭（中饭or晚饭）
